# https://mlflow.org

mlflow:
  _target_: reax.loggers.mlflow.MLFlowLogger
  experiment_name: e3response_QM9-NMR
  run_name: run_nmr_dev
  tracking_uri: http://127.0.0.1:5000
  tags:
    mlflow.user: ${oc.env:USER}
  prefix: ""
  artifact_location: null
