# https://mlflow.org

mlflow:
  _target_: reax.loggers.mlflow.MLFlowLogger
  experiment_name: e3response_Si-NMR
  run_name: run - nequip_nmr - LSfixed
  tags:
    mlflow.user: ${oc.env:USER}
  prefix: ""
  artifact_location: null
  # run_id: ""
